name: Publish to NuGet

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore --nologo
    - name: Build
      run: dotnet build --no-restore --nologo
    - name: Package
      run: dotnet pack -c Release --no-build --nologo /p:Version=${{ secrets.NUGET_VERSION }}
    - name: Publish
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
    
